name: Caching Assignment

on: [push, workflow_dispatch]

jobs:
  cache-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-step # We need an ID to check the output later
        uses: actions/cache@v4
        with:
          path: /tmp/dummy-cache-dir # A dummy path to store in the cache
          key: cache-248c59c

      - name: prime-cache-248c59c
        run: echo "Cache hit result - ${{ steps.cache-step.outputs.cache-hit }}"

      - name: Create dummy data to prime cache
        # This creates the directory so the cache action actually has something to save at the end of the job
        run: |
          mkdir -p /tmp/dummy-cache-dir
          echo "priming data" > /tmp/dummy-cache-dir/data.txt
